"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.markAsBestAnswer = exports.newReferral = exports.rateTutor = exports.tipTutor = exports.updateStreak = exports.buyCoins = exports.makeStripePayment = exports.cancelSession = exports.acceptSession = exports.requestNewSession = exports.subscribeToMailingList = exports.toggleAdmin = exports.messageCreated = exports.answerCommentDeleted = exports.answerCommentCreated = exports.questionCommentDeleted = exports.questionCommentCreated = exports.answerRated = exports.answerDeleted = exports.answerUpdated = exports.answerCreated = exports.questionDeleted = exports.questionUpdated = exports.questionCreated = exports.personalChatMediaDeleted = exports.personalChatsCreated = exports.userAccountPurchaseCoinsUpdated = exports.userAccountDailyLoginUpdated = exports.userAccountBestAnswersUpdated = exports.userAccountAnswersUpdated = exports.userAccountQuestionsUpdated = exports.userAccountSessionsUpdated = exports.userAccountTutorSessionsUpdated = exports.userAccountRatingsUpdated = exports.userProfileUpdated = exports.endSession = exports.resendEmails = exports.makeSuperAdmin = exports.runQuarterly = exports.runMonthly = exports.runWeekly = exports.runDaily = exports.authUserDeleted = exports.authUserCreated = void 0;
const admin = require("firebase-admin");
const auth_1 = require("./auth");
Object.defineProperty(exports, "authUserCreated", { enumerable: true, get: function () { return auth_1.authUserCreated; } });
Object.defineProperty(exports, "authUserDeleted", { enumerable: true, get: function () { return auth_1.authUserDeleted; } });
const makeSuperAdmin_1 = require("./requests/makeSuperAdmin");
Object.defineProperty(exports, "makeSuperAdmin", { enumerable: true, get: function () { return makeSuperAdmin_1.makeSuperAdmin; } });
const resendEmails_1 = require("./requests/resendEmails");
Object.defineProperty(exports, "resendEmails", { enumerable: true, get: function () { return resendEmails_1.resendEmails; } });
const endSession_1 = require("./requests/endSession");
Object.defineProperty(exports, "endSession", { enumerable: true, get: function () { return endSession_1.endSession; } });
const pubsub_1 = require("./pubsub");
Object.defineProperty(exports, "runDaily", { enumerable: true, get: function () { return pubsub_1.runDaily; } });
Object.defineProperty(exports, "runWeekly", { enumerable: true, get: function () { return pubsub_1.runWeekly; } });
Object.defineProperty(exports, "runMonthly", { enumerable: true, get: function () { return pubsub_1.runMonthly; } });
Object.defineProperty(exports, "runQuarterly", { enumerable: true, get: function () { return pubsub_1.runQuarterly; } });
const admins_1 = require("./onCall/roles/admins");
Object.defineProperty(exports, "toggleAdmin", { enumerable: true, get: function () { return admins_1.toggleAdmin; } });
const mailing_1 = require("./onCall/roles/mailing");
Object.defineProperty(exports, "subscribeToMailingList", { enumerable: true, get: function () { return mailing_1.subscribeToMailingList; } });
const requestNewSession_1 = require("./onCall/sessions/requestNewSession");
Object.defineProperty(exports, "requestNewSession", { enumerable: true, get: function () { return requestNewSession_1.requestNewSession; } });
const acceptSession_1 = require("./onCall/sessions/acceptSession");
Object.defineProperty(exports, "acceptSession", { enumerable: true, get: function () { return acceptSession_1.acceptSession; } });
const cancelSession_1 = require("./onCall/sessions/cancelSession");
Object.defineProperty(exports, "cancelSession", { enumerable: true, get: function () { return cancelSession_1.cancelSession; } });
const makePayment_1 = require("./onCall/payments/makePayment");
Object.defineProperty(exports, "makeStripePayment", { enumerable: true, get: function () { return makePayment_1.makeStripePayment; } });
const buyCoins_1 = require("./onCall/payments/buyCoins");
Object.defineProperty(exports, "buyCoins", { enumerable: true, get: function () { return buyCoins_1.buyCoins; } });
const updateStreak_1 = require("./onCall/users/updateStreak");
Object.defineProperty(exports, "updateStreak", { enumerable: true, get: function () { return updateStreak_1.updateStreak; } });
const tipTutor_1 = require("./onCall/users/tipTutor");
Object.defineProperty(exports, "tipTutor", { enumerable: true, get: function () { return tipTutor_1.tipTutor; } });
const rateTutor_1 = require("./onCall/users/rateTutor");
Object.defineProperty(exports, "rateTutor", { enumerable: true, get: function () { return rateTutor_1.rateTutor; } });
const newReferral_1 = require("./onCall/users/newReferral");
Object.defineProperty(exports, "newReferral", { enumerable: true, get: function () { return newReferral_1.newReferral; } });
const markAsBestAnswer_1 = require("./onCall/questions/markAsBestAnswer");
Object.defineProperty(exports, "markAsBestAnswer", { enumerable: true, get: function () { return markAsBestAnswer_1.markAsBestAnswer; } });
const users_1 = require("./modules/users/users");
Object.defineProperty(exports, "userProfileUpdated", { enumerable: true, get: function () { return users_1.userProfileUpdated; } });
Object.defineProperty(exports, "userAccountRatingsUpdated", { enumerable: true, get: function () { return users_1.userAccountRatingsUpdated; } });
Object.defineProperty(exports, "userAccountTutorSessionsUpdated", { enumerable: true, get: function () { return users_1.userAccountTutorSessionsUpdated; } });
Object.defineProperty(exports, "userAccountSessionsUpdated", { enumerable: true, get: function () { return users_1.userAccountSessionsUpdated; } });
Object.defineProperty(exports, "userAccountQuestionsUpdated", { enumerable: true, get: function () { return users_1.userAccountQuestionsUpdated; } });
Object.defineProperty(exports, "userAccountAnswersUpdated", { enumerable: true, get: function () { return users_1.userAccountAnswersUpdated; } });
Object.defineProperty(exports, "userAccountBestAnswersUpdated", { enumerable: true, get: function () { return users_1.userAccountBestAnswersUpdated; } });
Object.defineProperty(exports, "userAccountDailyLoginUpdated", { enumerable: true, get: function () { return users_1.userAccountDailyLoginUpdated; } });
Object.defineProperty(exports, "userAccountPurchaseCoinsUpdated", { enumerable: true, get: function () { return users_1.userAccountPurchaseCoinsUpdated; } });
const chats_1 = require("./modules/sessions/chats");
Object.defineProperty(exports, "personalChatsCreated", { enumerable: true, get: function () { return chats_1.personalChatsCreated; } });
Object.defineProperty(exports, "personalChatMediaDeleted", { enumerable: true, get: function () { return chats_1.personalChatMediaDeleted; } });
const comments_1 = require("./modules/questions/comments");
Object.defineProperty(exports, "questionCommentCreated", { enumerable: true, get: function () { return comments_1.questionCommentCreated; } });
Object.defineProperty(exports, "questionCommentDeleted", { enumerable: true, get: function () { return comments_1.questionCommentDeleted; } });
Object.defineProperty(exports, "answerCommentCreated", { enumerable: true, get: function () { return comments_1.answerCommentCreated; } });
Object.defineProperty(exports, "answerCommentDeleted", { enumerable: true, get: function () { return comments_1.answerCommentDeleted; } });
const questions_1 = require("./modules/questions/questions");
Object.defineProperty(exports, "questionCreated", { enumerable: true, get: function () { return questions_1.questionCreated; } });
Object.defineProperty(exports, "questionUpdated", { enumerable: true, get: function () { return questions_1.questionUpdated; } });
Object.defineProperty(exports, "questionDeleted", { enumerable: true, get: function () { return questions_1.questionDeleted; } });
const answers_1 = require("./modules/questions/answers");
Object.defineProperty(exports, "answerCreated", { enumerable: true, get: function () { return answers_1.answerCreated; } });
Object.defineProperty(exports, "answerUpdated", { enumerable: true, get: function () { return answers_1.answerUpdated; } });
Object.defineProperty(exports, "answerDeleted", { enumerable: true, get: function () { return answers_1.answerDeleted; } });
Object.defineProperty(exports, "answerRated", { enumerable: true, get: function () { return answers_1.answerRated; } });
const messages_1 = require("./modules/forms/messages");
Object.defineProperty(exports, "messageCreated", { enumerable: true, get: function () { return messages_1.messageCreated; } });
admin.initializeApp();
//# sourceMappingURL=index.js.map