// THIS FILE IS AUTO GENERATED

export enum IconNames {
  'admin' = 'admin',
  'answered' = 'answered',
  'answers' = 'answers',
  'apps' = 'apps',
  'best-answer' = 'best-answer',
  'bronze' = 'bronze',
  'chat' = 'chat',
  'class' = 'class',
  'close' = 'close',
  'create' = 'create',
  'dashboard' = 'dashboard',
  'e-wallet' = 'e-wallet',
  'gold' = 'gold',
  'google' = 'google',
  'Group 284' = 'Group 284',
  'hamburger' = 'hamburger',
  'home' = 'home',
  'member-since' = 'member-since',
  'nerd' = 'nerd',
  'notification-outline' = 'notification-outline',
  'notification' = 'notification',
  'profile-best-answers' = 'profile-best-answers',
  'questions-nav' = 'questions-nav',
  'questions' = 'questions',
  'right-nav' = 'right-nav',
  'schedule' = 'schedule',
  'search' = 'search',
  'sessions-attended' = 'sessions-attended',
  'sessions-hosted' = 'sessions-hosted',
  'signout' = 'signout',
  'study' = 'study',
  'tutors' = 'tutors',
  'user' = 'user',
  'views' = 'views'
}
